# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/echomary/workspace/ignoflash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/echomary/workspace/ignoflash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/echomary/workspace/ignoflash/CMakeFiles /home/echomary/workspace/ignoflash/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/echomary/workspace/ignoflash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IgnoFlash

# Build rule for target.
IgnoFlash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IgnoFlash
.PHONY : IgnoFlash

# fast build rule for target.
IgnoFlash/fast:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/build
.PHONY : IgnoFlash/fast

activex.o: activex.cpp.o
.PHONY : activex.o

# target to build an object file
activex.cpp.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/activex.cpp.o
.PHONY : activex.cpp.o

activex.i: activex.cpp.i
.PHONY : activex.i

# target to preprocess a source file
activex.cpp.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/activex.cpp.i
.PHONY : activex.cpp.i

activex.s: activex.cpp.s
.PHONY : activex.s

# target to generate assembly for a file
activex.cpp.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/activex.cpp.s
.PHONY : activex.cpp.s

backup.o: backup.cpp.o
.PHONY : backup.o

# target to build an object file
backup.cpp.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/backup.cpp.o
.PHONY : backup.cpp.o

backup.i: backup.cpp.i
.PHONY : backup.i

# target to preprocess a source file
backup.cpp.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/backup.cpp.i
.PHONY : backup.cpp.i

backup.s: backup.cpp.s
.PHONY : backup.s

# target to generate assembly for a file
backup.cpp.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/backup.cpp.s
.PHONY : backup.cpp.s

detect.o: detect.cpp.o
.PHONY : detect.o

# target to build an object file
detect.cpp.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/detect.cpp.o
.PHONY : detect.cpp.o

detect.i: detect.cpp.i
.PHONY : detect.i

# target to preprocess a source file
detect.cpp.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/detect.cpp.i
.PHONY : detect.cpp.i

detect.s: detect.cpp.s
.PHONY : detect.s

# target to generate assembly for a file
detect.cpp.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/detect.cpp.s
.PHONY : detect.cpp.s

dialog.o: dialog.cpp.o
.PHONY : dialog.o

# target to build an object file
dialog.cpp.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/dialog.cpp.o
.PHONY : dialog.cpp.o

dialog.i: dialog.cpp.i
.PHONY : dialog.i

# target to preprocess a source file
dialog.cpp.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/dialog.cpp.i
.PHONY : dialog.cpp.i

dialog.s: dialog.cpp.s
.PHONY : dialog.s

# target to generate assembly for a file
dialog.cpp.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/dialog.cpp.s
.PHONY : dialog.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/main.cpp.s
.PHONY : main.cpp.s

moc_dialog.o: moc_dialog.cxx.o
.PHONY : moc_dialog.o

# target to build an object file
moc_dialog.cxx.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/moc_dialog.cxx.o
.PHONY : moc_dialog.cxx.o

moc_dialog.i: moc_dialog.cxx.i
.PHONY : moc_dialog.i

# target to preprocess a source file
moc_dialog.cxx.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/moc_dialog.cxx.i
.PHONY : moc_dialog.cxx.i

moc_dialog.s: moc_dialog.cxx.s
.PHONY : moc_dialog.s

# target to generate assembly for a file
moc_dialog.cxx.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/moc_dialog.cxx.s
.PHONY : moc_dialog.cxx.s

netscape_linux32.o: netscape_linux32.cpp.o
.PHONY : netscape_linux32.o

# target to build an object file
netscape_linux32.cpp.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/netscape_linux32.cpp.o
.PHONY : netscape_linux32.cpp.o

netscape_linux32.i: netscape_linux32.cpp.i
.PHONY : netscape_linux32.i

# target to preprocess a source file
netscape_linux32.cpp.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/netscape_linux32.cpp.i
.PHONY : netscape_linux32.cpp.i

netscape_linux32.s: netscape_linux32.cpp.s
.PHONY : netscape_linux32.s

# target to generate assembly for a file
netscape_linux32.cpp.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/netscape_linux32.cpp.s
.PHONY : netscape_linux32.cpp.s

netscape_win32.o: netscape_win32.cpp.o
.PHONY : netscape_win32.o

# target to build an object file
netscape_win32.cpp.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/netscape_win32.cpp.o
.PHONY : netscape_win32.cpp.o

netscape_win32.i: netscape_win32.cpp.i
.PHONY : netscape_win32.i

# target to preprocess a source file
netscape_win32.cpp.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/netscape_win32.cpp.i
.PHONY : netscape_win32.cpp.i

netscape_win32.s: netscape_win32.cpp.s
.PHONY : netscape_win32.s

# target to generate assembly for a file
netscape_win32.cpp.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/netscape_win32.cpp.s
.PHONY : netscape_win32.cpp.s

patch.o: patch.cpp.o
.PHONY : patch.o

# target to build an object file
patch.cpp.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/patch.cpp.o
.PHONY : patch.cpp.o

patch.i: patch.cpp.i
.PHONY : patch.i

# target to preprocess a source file
patch.cpp.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/patch.cpp.i
.PHONY : patch.cpp.i

patch.s: patch.cpp.s
.PHONY : patch.s

# target to generate assembly for a file
patch.cpp.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/patch.cpp.s
.PHONY : patch.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/IgnoFlash.dir/build.make CMakeFiles/IgnoFlash.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... IgnoFlash"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... activex.o"
	@echo "... activex.i"
	@echo "... activex.s"
	@echo "... backup.o"
	@echo "... backup.i"
	@echo "... backup.s"
	@echo "... detect.o"
	@echo "... detect.i"
	@echo "... detect.s"
	@echo "... dialog.o"
	@echo "... dialog.i"
	@echo "... dialog.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... moc_dialog.o"
	@echo "... moc_dialog.i"
	@echo "... moc_dialog.s"
	@echo "... netscape_linux32.o"
	@echo "... netscape_linux32.i"
	@echo "... netscape_linux32.s"
	@echo "... netscape_win32.o"
	@echo "... netscape_win32.i"
	@echo "... netscape_win32.s"
	@echo "... patch.o"
	@echo "... patch.i"
	@echo "... patch.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

